# Generated by Django 5.2.7 on 2025-11-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('MST-1', 'MST-1'), ('MST-2', 'MST-2'), ('EST', 'End Semester')], max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
