# Generated by Django 5.2.7 on 2025-11-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('video', 'YouTube Video'), ('pdf', 'PDF Notes')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('video_id', models.CharField(blank=True, help_text='YouTube video ID (e.g., dQw4w9WgXcQ)', max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.subject')),
            ],
        ),
    ]
